export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: string;
  category: string;
  subcategory?: string;
  image?: string;
  isPopular?: boolean;
  allergens?: string[];
  deleted?: boolean;
}

export interface Campaign {
  id: string;
  title: string;
  description: string;
  image?: string;
  category?: string;
}

export interface Event {
  id: string;
  title: string;
  date: string;
  time: string;
  description: string;
  image?: string;
}

export interface HeroSlide {
  id: string;
  title: string;
  subtitle: string;
  highlight: string;
  description: string;
  image: string;
  buttonText: string;
}

export const CATEGORIES = [
  "Kampanyalar", "Yemekler", "Kadeh", "Şişeler", "Şarap", "Kokteyller", "Alkolsüz Kokteyller", "Biralar", "Shotlar", "Popüler", "Kahvaltı", "Kahveler", "Soğuk Kahveler", "Çaylar", "Atıştırmalıklar", "Salatalar", "Tatlılar", "Soğuk İçecekler", "Soft İçecekler"
];

export const MENU_DATA: MenuItem[] = [
  // --- POPÜLER SEÇİMLER (isPopular: true olanlar otomatik olarak Popüler Lezzetler kısmına gelir) ---
  {
    id: "p1",
    name: "BAMM Burger",
    description: "160gr dana köfte, karamelize soğan, cheddar peyniri, turşu, özel sos ve patates kızartması ile.",
    price: "420₺",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "p2",
    name: "PİNK TO BAMM",
    description: "BAMM'ın imza pembe kokteyli; votka, taze meyve özleri ve gizli dokunuşlar.",
    price: "460₺",
    category: "Kokteyller", 
    subcategory: "İmza Kokteylleri",
    isPopular: true,
  },
  // --- KAHVALTI ---
  {
    id: "kv_br1",
    name: "CRUASSİANT EL PESTO",
    description: "Cruassiant ekmeğinde; Pesto sos, Taze Domates, Mozarella, Roka ve Glaze ile servis edilir.",
    price: "140₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
    image: "https://images.unsplash.com/photo-1549466694-5fae5c4017f6?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "kv_br2",
    name: "MORNİNG BURGER",
    description: "Tereyağlı Burger ekmeğinde: Acuka, Roka, Peynir, Cheddar, Göz yumurta ile.",
    price: "250₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "kv_br3",
    name: "CRUASSİANT FORMACCİ",
    description: "Cruassiant Ekmeğinde; 3 Çeşit peynir ve Çörekotu ile servis edilir.",
    price: "140₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  {
    id: "kv_br4",
    name: "CAPRESE-WİCH",
    description: "200 Gram mayalı İtalyan ekmeği içine; Pesto, Domates, Salatalık, Izgara Yeşil Biber.",
    price: "220₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  {
    id: "kv_br5",
    name: "AMERİCAN BREAKFAST",
    description: "Ordövr Tabağında; 2 Adet Amerikan Sosis, 2 Göz yumurta, 3 Dilim Ballı Krep, Patates.",
    price: "210₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  {
    id: "kv_br6",
    name: "CRUASSİANT CLASSİCO",
    description: "Cruassiant ekmeğinde; Çırpılmış yumurta, Dana füme, Beyaz peynir, Roka ve Glaze sos.",
    price: "140₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  {
    id: "kv_br7",
    name: "TURKİSH BREAKFAST",
    description: "Haşlanmış Yada Sahanda Yumurta",
    price: "350₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  {
    id: "p4",
    name: "Turkish Breakfast (Serpme)",
    description: "Zengin peynir çeşitleri, zeytinler, ev yapımı reçeller, sucuklu yumurta, sınırsız çay ile (Kişi başı).",
    price: "480₺",
    category: "Kahvaltı",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "kv_br8",
    name: "ŞİPŞAK KAHVALTI",
    description: "Chedarlı simit, göz yumurta, peynir, patates, zeytin, salatalık, acuka, domates, nutella...",
    price: "200₺",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },
  // --- KAHVALTI - Omletler ---
  {
    id: "kv_om1",
    name: "Peynirli Omlet",
    description: "3 yumurta, beyaz peynir ve taze yeşillikler ile",
    price: "180₺",
    category: "Kahvaltı",
    subcategory: "Omletler",
  },
  {
    id: "kv_om2",
    name: "Mantarlı Omlet",
    description: "3 yumurta, kültür mantarı ve taze yeşillikler ile",
    price: "180₺",
    category: "Kahvaltı",
    subcategory: "Omletler",
  },
  {
    id: "kv_om3",
    name: "Dere Otlu Omlet",
    description: "3 yumurta, taze dereotu ve yeşillikler ile",
    price: "180₺",
    category: "Kahvaltı",
    subcategory: "Omletler",
  },
  {
    id: "kv_om4",
    name: "Sucuklu Omlet",
    description: "3 yumurta, dana sucuk dilimleri ve yeşillikler ile",
    price: "180₺",
    category: "Kahvaltı",
    subcategory: "Omletler",
  },
  {
    id: "kv_om5",
    name: "Sade Omlet",
    description: "3 yumurta ve taze yeşillikler ile",
    price: "110₺",
    category: "Kahvaltı",
    subcategory: "Omletler",
  },
  // --- KAHVALTI - Sahanda ---
  {
    id: "kv_sa1",
    name: "Sahanda Sade Yumurta",
    description: "2 adet yumurta sahanda tereyağı ile",
    price: "150₺",
    category: "Kahvaltı",
    subcategory: "Sahanda",
  },
  {
    id: "kv_sa2",
    name: "Sahanda Sucuklu Yumurta",
    description: "Sahanda Sucuklu Yumurta",
    price: "200₺",
    category: "Kahvaltı",
    subcategory: "Sahanda",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "kv_sa3",
    name: "Sahanda Kavurmalı Yumurta",
    description: "Dana kavurma ve 2 adet yumurta sahanda",
    price: "270₺",
    category: "Kahvaltı",
    subcategory: "Sahanda",
  },

  // --- KAHVALTI - Tostlar ---
  {
    id: "kv_to1",
    name: "Karışık Tost",
    description: "Domates, salatalık ve patates eşliğinde.",
    price: "200₺",
    category: "Kahvaltı",
    subcategory: "Tostlar",
  },
  {
    id: "kv_to2",
    name: "Kaşarlı Tost",
    description: "Domates, salatalık ve patates eşliğinde.",
    price: "180₺",
    category: "Kahvaltı",
    subcategory: "Tostlar",
  },
  {
    id: "kv_to3",
    name: "Bazlama Tost",
    description: "Domates, salatalık ve patates eşliğinde.",
    price: "220₺",
    category: "Kahvaltı",
    subcategory: "Tostlar",
  },
  {
    id: "kv4",
    name: "Kahvaltı Tabağı",
    description: "Klasik Türk kahvaltısı öğeleri; peynir, zeytin, domates, salatalık, yumurta, bal-kaymak.",
    price: "320 TL",
    category: "Kahvaltı",
    subcategory: "Breakfast",
  },

  // --- ATIŞTIRMALIKLAR ---
  {
    id: "a4",
    name: "PATATES KIZARTMASI",
    description: "DİP SOS EŞLİĞİNDE",
    price: "210₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a10",
    name: "PEYNİR TABAĞI",
    description: "İsli peynir, ezine peyniri, eski kaşar, örgü peyniri, cecil peyniri, kayısı, incir, üzüm, ceviz",
    price: "390₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a11",
    name: "Havuç Salatalık Kokteyl",
    description: "Havuç Salatalık Kokteyl",
    price: "160₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a12",
    name: "Salatalık Söğüş",
    description: "Salatalık Söğüş",
    price: "150₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a13",
    name: "Karışık Çerez",
    description: "Karışık Çerez",
    price: "190₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a14",
    name: "Tuzlu Fıstık",
    description: "Tuzlu Fıstık",
    price: "140₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a15",
    name: "Salatalık Turşu",
    description: "SALATALIK TURŞU",
    price: "150₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a16",
    name: "Küp Kaşar",
    description: "Küp Kaşar peyniri",
    price: "180₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a5",
    name: "SOĞAN HALKASI SEPETİ",
    description: "Patates eşliğinde soğan halkası dip sos.",
    price: "260₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a6",
    name: "ÇITIR CHICKEN FINGERS",
    description: "",
    price: "420₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a7",
    name: "LEZZET SEPETİ",
    description: "Çıtır tavuk parçaları, soğan halkası, misket köfte, sigara böreği, sosis, mozarella stick ve özel soslar.",
    price: "480₺",
    category: "Atıştırmalıklar",
    isPopular: true,
  },
  {
    id: "a8",
    name: "Paçanga Böreği",
    description: "2 adet paçanga ve patates kızartması",
    price: "270₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a9",
    name: "Çıtır Yufkalar",
    description: "1 Paçanga böreği, 2 rulo börek",
    price: "190₺",
    category: "Atıştırmalıklar",
  },
  {
    id: "a1",
    name: "Çıtır Tavuk Parçaları",
    description: "Özel panelenmiş çıtır tavuklar, ballı hardal sos ile.",
    price: "240 TL",
    category: "Atıştırmalıklar",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "a2",
    name: "BAMM Patates",
    description: "Özel baharat karışımlı elma dilim patates.",
    price: "160 TL",
    category: "Atıştırmalıklar",
  },
  {
    id: "a3",
    name: "Mozzarella Sticks",
    description: "6 adet panelenmiş mozzarella peyniri.",
    price: "220 TL",
    category: "Atıştırmalıklar",
    image: "https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&q=80&w=800",
  },

  // --- TOST & SANDVİÇ (Daha önce ayrıydı, şimdi Kahvaltı altında) ---
  {
    id: "ts1",
    name: "Bazlama Tost",
    description: "Özel bazlama ekmeğinde bol kaşar, sucuk ve domates salçası.",
    price: "240 TL",
    category: "Kahvaltı",
    subcategory: "Tostlar",
  },
  {
    id: "ts2",
    name: "Karışık Tost",
    description: "Tost ekmeğinde kaşar peyniri ve dana sucuk.",
    price: "210 TL",
    category: "Kahvaltı",
    subcategory: "Tostlar",
    image: "https://images.unsplash.com/photo-1525385133512-2f3bdd039054?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "ts3",
    name: "Kaşarlı Tost",
    description: "Tost ekmeğinde erimiş kaşar peyniri.",
    price: "180 TL",
    category: "Kahvaltı",
    subcategory: "Tostlar",
    image: "https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?auto=format&fit=crop&q=80&w=800",
  },

  // --- DÜRÜMLER & BOWL (Daha önce ayrıydı, şimdi Yemekler altında) ---
  {
    id: "db1",
    name: "Tavuklu Dürüm",
    description: "Lavaş içerisinde ızgara tavuk parçaları, yeşillik ve özel sos; yanında patates kızartması ile.",
    price: "280 TL",
    category: "Yemekler",
    subcategory: "Wrapler",
  },
  {
    id: "db2",
    name: "Köfteli Dürüm",
    description: "Lavaş içerisinde kasap köfte, domates, soğan ve yeşillik; yanında patates kızartması ile.",
    price: "320 TL",
    category: "Yemekler",
    subcategory: "Wrapler",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "db3",
    name: "Power Bowl",
    description: "Izgara tavuk, kinoa, avokado, mısır, çeri domates ve yeşillik karışımı.",
    price: "360 TL",
    category: "Yemekler",
    subcategory: "Wrapler",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  
  // --- BURGERLER ---
  {
    id: "b1",
    name: "Cheeseburger",
    description: "Dana köfte, çift cheddar, turşu, yeşillik, domates.",
    price: "410 TL",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "b2",
    name: "Chicken Burger",
    description: "Panelenmiş tavuk göğsü, özel mayonezli sos, yeşillik.",
    price: "360 TL",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&q=80&w=800",
  },

  // --- PİZZALAR ---
  {
    id: "z1",
    name: "BAMM Karışık Pizza",
    description: "Sucuk, sosis, mantar, mısır, zeytin, biber, mozzarella.",
    price: "410 TL",
    category: "Yemekler",
    subcategory: "Pizzalar",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "z2",
    name: "Pizza Margherita",
    description: "Özel pizza sosu, taze mozzarella, fesleğen.",
    price: "330 TL",
    category: "Yemekler",
    subcategory: "Pizzalar",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=800",
  },

  // --- MAKARNALAR ---
  {
    id: "m1",
    name: "Penne Arabiatta",
    description: "Acılı domates sosu, siyah zeytin, parmesan.",
    price: "310 TL",
    category: "Yemekler",
    subcategory: "Makarnalar",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "m2",
    name: "Spaghetti Bolognese",
    description: "Geleneksel kıymalı sos ve parmesan peyniri ile.",
    price: "350 TL",
    category: "Yemekler",
    subcategory: "Makarnalar",
    image: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?auto=format&fit=crop&q=80&w=800",
  },


  // --- SALATALAR ---
  {
    id: "s1",
    name: "IZGARA PİLİÇ GÖĞÜS SALATA",
    description: "Slice tavuk parçaları, maskolin yeşillik, domates, salatalık, havuç tako, özel sos ile",
    price: "350₺",
    category: "Salatalar",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "s2",
    name: "BEEF SALATA",
    description: "Slice et parçaları, maskolin yeşillikleri, domates, salatalık, havuç, tako, özel sos ile",
    price: "420₺",
    category: "Salatalar",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "s3",
    name: "SEZAR SALATA",
    description: "Izgara tavuk parçaları, iceberg marul, parmesan, kroton ekmek, sezar sos ile",
    price: "360₺",
    category: "Salatalar",
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "s4",
    name: "GREAK SALATA",
    description: "Küp domates, küp salatalık, küp soğan, küp peynir, dilim siyah zeytin, özel bamm salata sosu",
    price: "310₺",
    category: "Salatalar",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "s5",
    name: "KAJUN TAVUK SALATA",
    description: "Çıtır tavuk parçaları, maskolin yeşilliği, rende mozarella, domates, salatalık, tako dip sos ile",
    price: "350₺",
    category: "Salatalar",
    image: "https://images.unsplash.com/photo-1580013759032-c96505e24c1f?auto=format&fit=crop&q=80&w=800",
  },

  // --- YEMEKLER ---
  {
    id: "y1",
    name: "Tavuk Schnitzel",
    description: "Panelenmiş tavuk göğsü, patates salatası ve yeşillik ile.",
    price: "380 TL",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "y2",
    name: "Izgara Köfte",
    description: "Özel kasap köfte, ızgara sebze, pilav ve patates kızartması ile.",
    price: "440 TL",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "y3",
    name: "Beğendili Kebap",
    description: "Közlenmiş patlıcan beğendi üzerinde sote dana eti parçaları.",
    price: "560 TL",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
  },
  {
    id: "y4",
    name: "Mantar Soslu Tavuk",
    description: "Izgara tavuk göğsü, kremsi mantar sos, pilav ve haşlanmış sebze ile.",
    price: "390 TL",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "y5",
    name: "Cafe de Paris Steak",
    description: "Özel Cafe de Paris soslu dana bonfile dilimleri, patates kızartması ile.",
    price: "640 TL",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
  },

  // --- TATLILAR ---
  {
    id: "t1",
    name: "San Sebastian",
    description: "Çikolata sos eşliğinde akışkan İspanyol cheesekake.",
    price: "260₺",
    category: "Tatlılar",
    subcategory: "Soğuklar",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "t_ch",
    name: "Cheesecake",
    description: "Taze meyve soslu klasik cheesecake.",
    price: "220₺",
    category: "Tatlılar",
    subcategory: "Soğuklar",
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "t2",
    name: "Bavyera Sufle",
    description: "Sıcak Belçika çikolatası ve vanilyalı dondurma ile.",
    price: "240₺",
    category: "Tatlılar",
    subcategory: "Sıcaklar",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&q=80&w=800",
  },

  // --- KOKTEYLLER ---
  {
    id: "k1",
    name: "Kuzu Kulağı",
    description: "Taze kuzu kulağı otu aromalı ferahlatıcı imza kokteyl.",
    price: "410 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "k2",
    name: "Goshra",
    description: "Egzotik meyveler ve baharatlı rom ile hazırlanan imza kokteyl.",
    price: "400 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k3",
    name: "Baileys Brule",
    description: "Baileys, karamel ve kremsi dokulu tatlı bir bitiş.",
    price: "390 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k4",
    name: "Marshmallows",
    description: "Hafif, tatlı ve marshmallow aromalı yumuşak içimli kokteyl.",
    price: "380 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k5",
    name: "Rönesans",
    description: "Cin bazlı, taze baharatlar ve kırmızı meyvelerle hazırlanan sanatsal bir lezzet.",
    price: "330 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k6",
    name: "Mojito Çilek",
    description: "Taze çileklerle hazırlanan özel Mojito.",
    price: "400 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k7",
    name: "Peach Sprtiz",
    description: "Red Bull Peach Edition Campari Karpuz Dilim Limon",
    price: "400 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k8",
    name: "Stella",
    description: "Gin ve portakal likörünün yıldız uyumu. Mekanın yıldızı . masaların favorisi.",
    price: "380 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
    isPopular: true,
  },
  {
    id: "k9",
    name: "Romka",
    description: "Rom ve kahve likörü kısa ama etkili konuşur. Küçük bardak , büyük kafa",
    price: "380 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k10",
    name: "Cherry Kiss",
    description: "Vişne ve Ahududu Vodkasının tatlı öpücüğü.Bir yudum . sonra bir tane daha.",
    price: "340 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k11",
    name: "Chocco Porto",
    description: "Çikolata , Vodka ve Portakalın Tadı Çarpışması. Tatlı krizinin Alkollü çözümü",
    price: "350 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k12",
    name: "Apple Gin Fizz",
    description: "Elma , Gin ve Soda.. Hafif , Ferah ve Sohbet Uzatan Tiplerden",
    price: "400 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k13",
    name: "Jager Soft",
    description: "Jager' in Enerjik versiyonu . Sohbeti Hızlandırır, Geceyi uzatır .",
    price: "420 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k14",
    name: "Jager Asid",
    description: "Jager + Limon + Soda . Ekşi , Ferah ve Beklenmedik Derecede Bağımlılık yapıcı",
    price: "420 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k15",
    name: "Fındık İhtilali",
    description: "Fındık Aroması , Vodka ve süt . Tatlı başlar devrim gibi devam eder",
    price: "320 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k16",
    name: "Baileys Martini",
    description: "Baileys , Vodka ve Espresso . Tatlı mi içki mi Karar veremeyenler İçin .",
    price: "340 TL",
    category: "Kokteyller", subcategory: "İmza Kokteylleri",
  },
  {
    id: "k17",
    name: "Stawberry Daiquri",
    description: "",
    price: "380 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k18",
    name: "Whiskey Sour",
    description: "",
    price: "430 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k19",
    name: "Margarita",
    description: "",
    price: "320 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k20",
    name: "Sex On The Beach",
    description: "",
    price: "320 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k21",
    name: "Mojito",
    description: "",
    price: "400 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k22",
    name: "LONG İSLAND",
    description: "",
    price: "450 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k23",
    name: "COSMOPOLITAN",
    description: "",
    price: "340 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k24",
    name: "GİNN TONİK",
    description: "",
    price: "320 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k25",
    name: "Espersso Martini",
    description: "",
    price: "400 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k26",
    name: "Cuba Libre",
    description: "",
    price: "360 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k27",
    name: "Hendricks Gin Tonic",
    description: "",
    price: "390 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k28",
    name: "Duble Gin Tonic",
    description: "",
    price: "390 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k29",
    name: "Sangria",
    description: "",
    price: "320 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k30",
    name: "Negroni",
    description: "",
    price: "400 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k31",
    name: "Black Russian",
    description: "",
    price: "360 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k32",
    name: "White Russian",
    description: "",
    price: "360 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k33",
    name: "Tekila Sunrise",
    description: "",
    price: "360 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k34",
    name: "Daiquri",
    description: "",
    price: "380 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k35",
    name: "Pinacolado",
    description: "",
    price: "380 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },
  {
    id: "k36",
    name: "Lynchburg Lemonade",
    description: "",
    price: "450 TL",
    category: "Kokteyller", subcategory: "Dünya Klasikleri",
  },

  // --- BİRALAR ---
  {
    id: "beer1",
    name: "Tuborg 50cl Fıçı",
    description: "",
    price: "170 TL",
    category: "Biralar",
    subcategory: "Fıçı Biralar",
  },
  {
    id: "beer2",
    name: "Tuborg 33cl Fıçı",
    description: "",
    price: "130 TL",
    category: "Biralar",
    subcategory: "Fıçı Biralar",
  },
  {
    id: "beer3",
    name: "Carlsberg 33cl Fıçı",
    description: "",
    price: "135 TL",
    category: "Biralar",
    subcategory: "Fıçı Biralar",
  },
  {
    id: "beer4",
    name: "Carlsberg 50cl Fıçı",
    description: "",
    price: "180 TL",
    category: "Biralar",
    subcategory: "Fıçı Biralar",
  },
  {
    id: "beer_sise1",
    name: "Tuborg Gold 50cl Şişe",
    description: "",
    price: "190 TL",
    category: "Biralar",
    subcategory: "Şişe Biralar",
  },
  {
    id: "beer_sise2",
    name: "Tuborg Gold 33cl Şişe",
    description: "",
    price: "145 TL",
    category: "Biralar",
    subcategory: "Şişe Biralar",
  },
  {
    id: "beer_sise3",
    name: "Carlsberg 50cl Şişe",
    description: "",
    price: "200 TL",
    category: "Biralar",
    subcategory: "Şişe Biralar",
  },
  {
    id: "beer_sise4",
    name: "Carlsberg 33cl Şişe",
    description: "",
    price: "150 TL",
    category: "Biralar",
    subcategory: "Şişe Biralar",
  },
  {
    id: "beer_sise5",
    name: "Mexicano Bardak",
    description: "",
    price: "15 TL",
    category: "Biralar",
    subcategory: "Şişe Biralar",
  },
  {
    id: "beer_kova1",
    name: "4'lü Tuborg Kova Menü",
    description: "",
    price: "900 TL",
    category: "Biralar",
    subcategory: "Kova Biralar",
  },
  {
    id: "beer_kova2",
    name: "6'lı Tuborg Kova Menü",
    description: "",
    price: "1150 TL",
    category: "Biralar",
    subcategory: "Kova Biralar",
  },
  {
    id: "beer_kova3",
    name: "4'lü Carlsberg Kova Menü",
    description: "",
    price: "960 TL",
    category: "Biralar",
    subcategory: "Kova Biralar",
  },
  {
    id: "beer_kova4",
    name: "6'lı Carlsberg Kova Menü",
    description: "",
    price: "1200 TL",
    category: "Biralar",
    subcategory: "Kova Biralar",
  },
  {
    id: "beer_kova5",
    name: "4'lü Tuborg Filtresiz Kova Menü",
    description: "",
    price: "900 TL",
    category: "Biralar",
    subcategory: "Kova Biralar",
  },
  {
    id: "beer_craft1",
    name: "Tuborg Amber 50cl",
    description: "",
    price: "200 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_craft2",
    name: "Tuborg Filtresiz 50cl",
    description: "",
    price: "210 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_craft3",
    name: "Weihenstephaner 33cl",
    description: "",
    price: "260 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_craft4",
    name: "Guinness 44cl",
    description: "",
    price: "275 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_craft5",
    name: "1664 Blanc 33cl",
    description: "",
    price: "175 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_craft6",
    name: "Tuborg İce 33cl",
    description: "",
    price: "140 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_ithal1",
    name: "Sol 33cl",
    description: "",
    price: "190 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_ithal2",
    name: "Tuborg Desperados 33cl",
    description: "",
    price: "255 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },
  {
    id: "beer_ithal3",
    name: "Carlsberg Luna",
    description: "",
    price: "220 TL",
    category: "Biralar",
    subcategory: "İthal Biralar",
  },

  // --- SICAK İÇECEKLER ---
  {
    id: "h1",
    name: "Türk Kahvesi",
    description: "Geleneksel Türk kahvesi, lokum eşliğinde.",
    price: "90 TL",
    category: "Sıcak İçecekler",
    image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "h2",
    name: "Caffe Latte",
    description: "Espresso ve kremsi süt köpüğü.",
    price: "120 TL",
    category: "Sıcak İçecekler",
    image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "h3",
    name: "Cappuccino",
    description: "Espresso, yoğun süt ve süt köpüğü.",
    price: "125 TL",
    category: "Sıcak İçecekler",
  },
  {
    id: "h4",
    name: "Americano",
    description: "Espresso ve sıcak suyun sade buluşması.",
    price: "115 TL",
    category: "Sıcak İçecekler",
    image: "https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "h5",
    name: "Bardak Çay",
    description: "Taze demlenmiş Rize çayı.",
    price: "35 TL",
    category: "Sıcak İçecekler",
  },
  {
    id: "h6",
    name: "Bitki Çayları",
    description: "Adaçayı, Ihlamur, Kış Çayı, Yeşil Çay seçekenekleri ile.",
    price: "110 TL",
    category: "Sıcak İçecekler",
    image: "https://images.unsplash.com/photo-1563822249548-9a72b6353cd1?auto=format&fit=crop&q=80&w=800",
  },

  // --- SOĞUK İÇECEKLER ---
  {
    id: "sd1",
    name: "Ev Yapımı Limonata",
    description: "Taze nane ve limonun ferahlatıcı uyumu.",
    price: "135 TL",
    category: "Soğuk İçecekler",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sd2",
    name: "Çilekli Limonata",
    description: "Taze çilek püreli ev yapımı limonata.",
    price: "150 TL",
    category: "Soğuk İçecekler",
    image: "https://images.unsplash.com/photo-1510626176961-4b57d4fbad03?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "sd3",
    name: "Churchill",
    description: "Soda, taze limon suyu ve tuz.",
    price: "85 TL",
    category: "Soğuk İçecekler",
  },
  {
    id: "sd4",
    name: "Iced Latte",
    description: "Espresso, soğuk süt ve buz.",
    price: "130 TL",
    category: "Soğuk İçecekler",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=800",
  },

  // --- SOFT İÇECEKLER ---
  {
    id: "soft_1",
    name: "Coca Cola 330ml",
    description: "",
    price: "90₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_2",
    name: "Fanta 330ml",
    description: "",
    price: "90₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_3",
    name: "Sprite 330ml",
    description: "",
    price: "90₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_4",
    name: "Ayran",
    description: "",
    price: "85₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_5",
    name: "Meyve Suyu",
    description: "",
    price: "85₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_6",
    name: "Coca Cola Zero 330ml",
    description: "",
    price: "90₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_7",
    name: "Fuse Tea",
    description: "",
    price: "90₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_8",
    name: "Taze Sıkılmış Portakal Suyu",
    description: "",
    price: "160₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_9",
    name: "Uludağ Meyveli Soda",
    description: "",
    price: "70₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_10",
    name: "Uludağ Maden Suyu",
    description: "",
    price: "70₺",
    category: "Soft İçecekler",
  },
  {
    id: "soft_11",
    name: "Erikli Su",
    description: "",
    price: "45₺",
    category: "Soft İçecekler",
  },

  // --- ALKOLSÜZ KOKTEYLLER ---
  {
    id: "alk_kok_1",
    name: "Pink",
    description: "",
    price: "220₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_2",
    name: "Green Matcha Latte",
    description: "",
    price: "170₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_3",
    name: "Coffee Breeze",
    description: "",
    price: "220₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_4",
    name: "Hulk",
    description: "",
    price: "220₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_5",
    name: "Hermonie Ginger",
    description: "",
    price: "220₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_6",
    name: "Blue Matcha Latte",
    description: "",
    price: "170₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Healthy Detox",
  },
  {
    id: "alk_kok_7",
    name: "Suprise Me",
    description: "",
    price: "320₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Smoothie",
  },
  {
    id: "alk_kok_8",
    name: "Elixir",
    description: "",
    price: "320₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Smoothie",
  },
  {
    id: "alk_kok_9",
    name: "I Love My Self",
    description: "",
    price: "320₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Smoothie",
  },
  {
    id: "alk_kok_10",
    name: "Duracell",
    description: "",
    price: "320₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Smoothie",
  },
  {
    id: "alk_kok_11",
    name: "Yummy Yummy",
    description: "",
    price: "320₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Smoothie",
  },
  {
    id: "alk_kok_12",
    name: "Oreo Bomb",
    description: "",
    price: "290₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_13",
    name: "Nutella Milkshake",
    description: "",
    price: "290₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_14",
    name: "Biscoff Lotus Milkshake",
    description: "",
    price: "290₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_15",
    name: "Brain Boost",
    description: "",
    price: "290₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_16",
    name: "Honey Bunny",
    description: "",
    price: "290₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_17",
    name: "Çilekli Milkshake",
    description: "",
    price: "270₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_18",
    name: "Çikolata Milkshake",
    description: "",
    price: "270₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_19",
    name: "Vanilya Milkshake",
    description: "",
    price: "270₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_20",
    name: "Karamel Milkshake",
    description: "",
    price: "270₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_21",
    name: "Orman Meyveli Milkshake",
    description: "",
    price: "270₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Milkshakes",
  },
  {
    id: "alk_kok_22",
    name: "Karpuz Frozen",
    description: "",
    price: "210₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Frozen",
  },
  {
    id: "alk_kok_23",
    name: "Orman Meyveli Frozen",
    description: "",
    price: "210₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Frozen",
  },
  {
    id: "alk_kok_24",
    name: "Mango Frozen",
    description: "",
    price: "210₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Frozen",
  },
  {
    id: "alk_kok_25",
    name: "Çilek Frozen",
    description: "",
    price: "210₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Frozen",
  },
  {
    id: "alk_kok_26",
    name: "Kavun Frozen",
    description: "",
    price: "210₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Frozen",
  },
  {
    id: "alk_kok_27",
    name: "Orman Meyveli Limonata",
    description: "",
    price: "190₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Limonata",
  },
  {
    id: "alk_kok_28",
    name: "Çilekli Limonata",
    description: "",
    price: "195₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Limonata",
  },
  {
    id: "alk_kok_29",
    name: "Uludağ Limonata",
    description: "",
    price: "165₺",
    category: "Alkolsüz Kokteyller",
    subcategory: "Limonata",
  },

  // --- SOĞUK KAHVELER ---
  {
    id: "sog_kah_1",
    name: "Patlayan İce Latte",
    description: "",
    price: "155₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_2",
    name: "İce Latte",
    description: "",
    price: "145₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_3",
    name: "İce Americano",
    description: "",
    price: "135₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_4",
    name: "İce mocha",
    description: "",
    price: "155₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_5",
    name: "İce White Mocha",
    description: "",
    price: "155₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_6",
    name: "Aroma",
    description: "",
    price: "30₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_7",
    name: "Frappe",
    description: "",
    price: "170₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_8",
    name: "Blue Matcha Latte Coffee",
    description: "",
    price: "190₺",
    category: "Soğuk Kahveler",
  },
  {
    id: "sog_kah_9",
    name: "Green Matcha Latte Coffee",
    description: "",
    price: "190₺",
    category: "Soğuk Kahveler",
  },

  // --- KAMPANYALAR ---
  {
    id: "camp_piz_1",
    name: "1+1 PİZZA KAMPANYA",
    description: "SEÇECEĞİNİZ TÜM PİZZALARDA 1 ALANA 1 BEDAVA SADECE CUMARTESİ HARİÇ...",
    price: "1₺",
    category: "Kampanyalar",
    subcategory: "1+1",
  },
  {
    id: "camp_kok_1",
    name: "1+1 KOKTEYL PAZARTESİ VE SALI",
    description: "PAZARTESİ VE SALI GÜNLERİ TÜM KOKTEYLLERDE 1 ALANA 1 BEDAVA",
    price: "1₺",
    category: "Kampanyalar",
    subcategory: "1+1",
  },
  {
    id: "camp_tav_1",
    name: "1+1 TAVUK KAMPANYA",
    description: "SEÇECEĞİNİZ TÜM TAVUK YEMEKLERİNDE 1 ALANA 1 BEDAVA SADECE CUMARTESİ...",
    price: "1₺",
    category: "Kampanyalar",
    subcategory: "1+1",
  },
  {
    id: "camp_sarap_1",
    name: "ŞARAP KAMPANYA (ŞARAPSIZ OLMAZ DEDİK)",
    description: "HAFTANIN HER GÜNÜ BEYAZ - KIRMIZI...",
    price: "850₺",
    category: "Kampanyalar",
    subcategory: "Şarap",
  },
  {
    id: "camp_shot_1",
    name: "KARMAKARIŞIK SHOT",
    description: "DİLEDİĞİNİZ TÜM SHOTLARDAN TOPLAM 10 ADETLİK SHOT TAHTAMIZ 1250TL",
    price: "1250₺",
    category: "Kampanyalar",
    subcategory: "Shoot",
  },
  {
    id: "camp_fici_1",
    name: "MEXİCO DAYS",
    description: "",
    price: "120₺",
    category: "Kampanyalar",
    subcategory: "Fıçı Kampanya",
  },
  {
    id: "camp_fici_2",
    name: "BU MASA DAĞILMAZ 4 ADET BİRA VE LEZZET SEPETİ",
    description: "Seçeceğiniz 4 ad. bira, yanında Lezzet Sepeti",
    price: "990₺",
    category: "Kampanyalar",
    subcategory: "Fıçı Kampanya",
  },
  
  // --- YEMEKLER ---
  {
    id: "yem_be1",
    name: "KÖRİ SOSLU TAVUK",
    description: "Kuşbaşı piliç, tagliatelli makarna, renkli biber, maskolin yeşillikleri, mantar",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=800",
    isPopular: true,
  },
  {
    id: "yem_be2",
    name: "MEXICAN TAVUK",
    description: "Kuşbaşı piliç, tagliatelli makarna, renkli biber, maskolin yeşillikleri",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
    image: "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_be3",
    name: "SOYA SOSLU TAVUK",
    description: "Kuşbaşı piliç, renkli biber, tagliatelli makarna, maskolin yeşillikleri",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
    image: "https://images.unsplash.com/photo-1598514982205-f36b96d1e8d4?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_be4",
    name: "IZGARA TAVUK PİRZOLA",
    description: "Dağ kekikleriyle marine edilmiş pirzola, tagliatelli makarna, maskolin yeşillikleri",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be5",
    name: "Tavuk Kül Bastı",
    description: "Sütle marine edilmiş tavuk, tagliatelli makarna, maskolin yeşillikleri domates ve salatalık ile",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be6",
    name: "MANTAR SOSLU PİLİÇ IZGARA",
    description: "Izgara tavuk, özel mantar sosu, tagliatelli makarna, cızlama",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be7",
    name: "KREMALI MANTARLI TAVUK",
    description: "Kuşbaşı piliç, tagliatelli makarna, renkli biber, maskolin yeşillikleri",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be8",
    name: "BBQ SOSLU TAVUK",
    description: "Kuşbaşı piliç, tagliatelli makarna, renkli biber, maskolin yeşillikleri",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be9",
    name: "CAFE DE PARIS SOSLU TAVUK",
    description: "Kuşbaşı piliç, tagliatelli makarna, maskolin yeşillikleri, cafe de pari sos, mantar",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be10",
    name: "Ballı Hardallı Tavuk",
    description: "Kuşbaşı piliç, özel ballı hardal sosu, tagliatelli makarna ve yeşillik ile",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },
  {
    id: "yem_be11",
    name: "Sweet Chili",
    description: "Kuşbaşı piliç, sweet chili sosu, tagliatelli makarna ve yeşillik ile",
    price: "395₺",
    category: "Yemekler",
    subcategory: "Beyaz Etler",
  },

  // --- YEMEKLER - Kırmızı Etler ---
  {
    id: "yem_ke1",
    name: "Saç Tava",
    description: "Mükemmel bonfile eşliğinde, renkli biber, arpacık soğan, domates",
    price: "600₺",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
    image: "https://images.unsplash.com/photo-1551028150-64b9f398f678?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_ke2",
    name: "BEĞENDİLİ IZGARA KÖFTE",
    description: "Kaburga köfte, pörpülenmiş patlıcan, maskolin yeşillikleri, domates, biber",
    price: "510₺",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_ke3",
    name: "DANA LOKUM",
    description: "Enfes bonfile ile tereyağının birleşimi",
    price: "710₺",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
  },
  {
    id: "yem_ke4",
    name: "IZGARA KÖFTE",
    description: "Kaburga köfte, patates, maskolin yeşillikleri, domates, biber",
    price: "480₺",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
  },
  {
    id: "yem_ke5",
    name: "ÇÖKERTME KEBABI",
    description: "Kibrit patates üzerinde marine edilmiş et dilimleri, yoğurt and özel domates sosu ile",
    price: "590₺",
    category: "Yemekler",
    subcategory: "Kırmızı Etler",
    isPopular: true,
  },

  // --- YEMEKLER - Burgerler ---
  {
    id: "yem_bu1",
    name: "MUSHROOM SMASH BURGER",
    description: "Burger Ekmeğine; 120Gr. Smashlenmiş Dana eti, Burger sosumuz ve Mantar özel sosu",
    price: "370₺",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_bu2",
    name: "FÜME BURGER",
    description: "Burger ekmeğinde; 120 Gram Dana Eti, 2 Dilim Cheddar, Burger Sosu, 1 Dilim Füme Et",
    price: "420₺",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_bu3",
    name: "SMASH BURGER",
    description: "Burger Ekmeğinde; 120 Gram Dana Eti, 2 Dilim Cheddar, Burger Sosu, Ve Smash Tekniği",
    price: "340₺",
    category: "Yemekler",
    subcategory: "Burgerler",
    image: "https://images.unsplash.com/photo-1550317144-b38c5f09a911?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_bu4",
    name: "CHICKEN KING BURGER",
    description: "Burger Ekmeğine; 120 Gram Panelenmiş Çıtır Tavuk, Iceberg, Ekşi Burger Sosu, Turşu",
    price: "260₺",
    category: "Yemekler",
    subcategory: "Burgerler",
  },
  {
    id: "yem_bu5",
    name: "Tekli Slider Burger",
    description: "Smash köfte, cheddar peyniri ve burger sos",
    price: "90₺",
    category: "Yemekler",
    subcategory: "Burgerler",
  },
  {
    id: "yem_bu6",
    name: "Üçlü Slider Burger",
    description: "60gr smash köfte, cheddar peyniri, burger sos, yanında patates ile",
    price: "320₺",
    category: "Yemekler",
    subcategory: "Burgerler",
  },
  {
    id: "yem_bu7",
    name: "BBQ Tiftik Burger",
    description: "120gr tiftik dana kaburga, cheddar peyniri, roka, bbq sos ile",
    price: "435₺",
    category: "Yemekler",
    subcategory: "Burgerler",
  },

  // --- YEMEKLER - Makarnalar ---
  {
    id: "yem_ma1",
    name: "PENNE ARABİATA",
    description: "Domates sos, fesleğen, dilim siyah zeytin, parmesan",
    price: "310₺",
    category: "Yemekler",
    subcategory: "Makarnalar",
  },
  {
    id: "yem_ma2",
    name: "SPHAGETTİ BOLOGNESE",
    description: "Bolognese sos, fesleğen, parmesan",
    price: "330₺",
    category: "Yemekler",
    subcategory: "Makarnalar",
  },
  {
    id: "yem_ma3",
    name: "TAVUKLU TAGLIATELLİ",
    description: "Julien tavuk parçaları, krema sos, parmesan, mantar",
    price: "330₺",
    category: "Yemekler",
    subcategory: "Makarnalar",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_ma4",
    name: "SEBZELİ TAGLIATELLİ",
    description: "Kabak, havuç, mantar, renkli biber krema sos, parmesan",
    price: "280₺",
    category: "Yemekler",
    subcategory: "Makarnalar",
  },
  {
    id: "yem_ma5",
    name: "BEEF TAGLIATELLİ",
    description: "Julien et parçaları, renkli biber, krema sos, parmesan, mantar",
    price: "340₺",
    category: "Yemekler",
    subcategory: "Makarnalar",
  },

  // --- YEMEKLER - Pizzalar ---
  {
    id: "yem_pi1",
    name: "CHICKEN OLYMPUS PİZZA",
    description: "Pizza sos, mozarella, julien tavuk parçaları, renkli biber, jelapone, mısır, taze roka",
    price: "390₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
  },
  {
    id: "yem_pi2",
    name: "Mantarlı Pizza",
    description: "Pizza sos, mozarella, mantar, taze roka",
    price: "360₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
  },
  {
    id: "yem_pi3",
    name: "EL TURCO PİZZA",
    description: "Pizza sos, mozarella, sucuk, mantar, renkli biber, zeytin, mısır",
    price: "380₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_pi4",
    name: "MEAT OLYMPUS PİZZA",
    description: "Pizza sos, mozarella, julien et parçaları, renkli biber, jelapone, mısır, taze roka",
    price: "420₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
    image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_pi5",
    name: "MARGHERİTA PİZZA",
    description: "Pizza sos, mozarella, taze roka, parmesan",
    price: "340₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_pi6",
    name: "PEPERONİ PİZZA",
    description: "Pizza sos, mozarella, peperoni sucuk",
    price: "360₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
  },
  {
    id: "yem_pi7",
    name: "Bamm Special Pizza",
    description: "Şefin özel pizza sosu, mozarella and zengin garnitürler ile",
    price: "470₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
  },
  {
    id: "yem_pi8",
    name: "Vejeteryan Pizza",
    description: "Mantar, biber, mısır, zeytin, mozarella and domates sos ile",
    price: "350₺",
    category: "Yemekler",
    subcategory: "Pizzalar",
  },
  {
    id: "yem_wr1",
    name: "SOYA SOSLU TAVUK WRAP",
    description: "180 gr piliç, Soya sos, krema, tortilla, renkli biber, patates ve dip sos eşliğinde",
    price: "320₺",
    category: "Yemekler",
    subcategory: "Wrapler",
  },
  {
    id: "yem_wr2",
    name: "KREMALI MANTARLI TAVUK WRAP",
    description: "180 gr piliç, Mantar, krema, renkli biber, tortilla, patates ve dip sos eşliğinde",
    price: "295₺",
    category: "Yemekler",
    subcategory: "Wrapler",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: "yem_wr3",
    name: "KÖFTE WRAP",
    description: "180 gr Dana köfte, maskolin yeşillikleri, patates ve dip sos eşliğinde",
    price: "330₺",
    category: "Yemekler",
    subcategory: "Wrapler",
  },
  {
    id: "yem_wr4",
    name: "BEEF WRAP",
    description: "180 gr Antrikot, maskolin yeşillikleri, patates ve dip sos eşliğinde, coleslaw salata",
    price: "410₺",
    category: "Yemekler",
    subcategory: "Wrapler",
  },
  // --- KADEH ---
  {
    id: "kad_vo2",
    name: "Absolut tek",
    description: "",
    price: "320₺",
    category: "Kadeh",
    subcategory: "Vodka",
  },
  {
    id: "kad_vo3",
    name: "Absolut Duble",
    description: "",
    price: "390₺",
    category: "Kadeh",
    subcategory: "Vodka",
  },
  {
    id: "kad_vo4",
    name: "Absolut Shot",
    description: "",
    price: "240₺",
    category: "Kadeh",
    subcategory: "Vodka",
  },
  {
    id: "kad_gi1",
    name: "Beefeater Gin Tek",
    description: "",
    price: "340₺",
    category: "Kadeh",
    subcategory: "Gin",
  },
  {
    id: "kad_gi2",
    name: "Beefeater Gin Duble",
    description: "",
    price: "410₺",
    category: "Kadeh",
    subcategory: "Gin",
  },
  {
    id: "kad_gi3",
    name: "Beefeater Gin Shot",
    description: "",
    price: "175₺",
    category: "Kadeh",
    subcategory: "Gin",
  },
  {
    id: "kad_gi4",
    name: "Hendriks Gin Tek",
    description: "",
    price: "420₺",
    category: "Kadeh",
    subcategory: "Gin",
  },
  {
    id: "kad_gi5",
    name: "Hendriks Gin Duble",
    description: "",
    price: "490₺",
    category: "Kadeh",
    subcategory: "Gin",
  },
  {
    id: "kad_ra1",
    name: "Yeni Rakı Tek",
    description: "",
    price: "230₺",
    category: "Kadeh",
    subcategory: "Rakı",
  },
  {
    id: "kad_ra2",
    name: "Yeni Rakı Duble",
    description: "",
    price: "320₺",
    category: "Kadeh",
    subcategory: "Rakı",
  },
  {
    id: "kad_vi1",
    name: "Ballantines Tek",
    description: "",
    price: "360₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi2",
    name: "Ballantines Duble",
    description: "",
    price: "420₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi3",
    name: "Chivas 12 Tek",
    description: "",
    price: "390₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi4",
    name: "Chivas 12 Duble",
    description: "",
    price: "470₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi5",
    name: "Jack Daniels Tek",
    description: "",
    price: "405₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi6",
    name: "Jack Daniels Duble",
    description: "",
    price: "490₺",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi7",
    name: "Red Label Tek",
    description: "",
    price: "-",
    category: "Kadeh",
    subcategory: "Viski",
  },
  {
    id: "kad_vi8",
    name: "Red Label Duble",
    description: "",
    price: "-",
    category: "Kadeh",
    subcategory: "Viski",
  },
  // --- ŞARAP ---
  {
    id: "sar_1",
    name: "Rose Kadeh",
    description: "",
    price: "250₺",
    category: "Şarap",
    subcategory: "Kadeh",
  },
  {
    id: "sar_2",
    name: "Beyaz Kadeh",
    description: "",
    price: "250₺",
    category: "Şarap",
    subcategory: "Kadeh",
  },
  {
    id: "sar_3",
    name: "Kırmızı Kadeh",
    description: "",
    price: "250₺",
    category: "Şarap",
    subcategory: "Kadeh",
  },
  {
    id: "sar_4",
    name: "Suvla Kilitbahir Beyaz",
    description: "",
    price: "750₺",
    category: "Şarap",
    subcategory: "Şişeler",
  },
  {
    id: "sar_5",
    name: "Suvla Kilitbahir Kırmızı",
    description: "",
    price: "750₺",
    category: "Şarap",
    subcategory: "Şişeler",
  },
  {
    id: "sar_6",
    name: "Suvla Kilitbahir Rose",
    description: "",
    price: "750₺",
    category: "Şarap",
    subcategory: "Şişeler",
  },
  // --- ŞİŞELER ---
  {
    id: "sis_vo1",
    name: "Absolut 70cl",
    description: "",
    price: "3250₺",
    category: "Şişeler",
    subcategory: "Vodka",
  },
  {
    id: "sis_vo2",
    name: "Absolut 35cl",
    description: "",
    price: "2250₺",
    category: "Şişeler",
    subcategory: "Vodka",
  },
  {
    id: "sis_vo3",
    name: "Smirnof 70cl",
    description: "",
    price: "3600₺",
    category: "Şişeler",
    subcategory: "Vodka",
  },
  {
    id: "sis_gi1",
    name: "Beefeater Gin 70cl",
    description: "",
    price: "3600₺",
    category: "Şişeler",
    subcategory: "Gin",
  },
  {
    id: "sis_gi2",
    name: "Hendricks Gin 70cl",
    description: "",
    price: "6700₺",
    category: "Şişeler",
    subcategory: "Gin",
  },
  {
    id: "sis_ra1",
    name: "Yeni Rakı 35cl",
    description: "",
    price: "2250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra2",
    name: "Tekirdağ Altın Seri 35cl",
    description: "",
    price: "2250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra3",
    name: "Beylerbeyi Göbek 35cl",
    description: "",
    price: "2250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra4",
    name: "Yeni Rakı 70cl",
    description: "",
    price: "3250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra5",
    name: "Tekirdağ Altın Seri 70cl",
    description: "",
    price: "3250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra6",
    name: "Beylerbeyi Göbek 70cl",
    description: "",
    price: "3250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra7",
    name: "Beylerbeyi Göbek 50cl",
    description: "",
    price: "3000₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_ra8",
    name: "Beylerbeyi Göbek 100cl",
    description: "",
    price: "4250₺",
    category: "Şişeler",
    subcategory: "Rakı",
  },
  {
    id: "sis_vi1",
    name: "Chivas Smooth & Smooky 35cl",
    description: "",
    price: "2500₺",
    category: "Şişeler",
    subcategory: "Viski",
  },
  {
    id: "sis_vi2",
    name: "Chivas Smooth & Smooky 70cl",
    description: "",
    price: "4600₺",
    category: "Şişeler",
    subcategory: "Viski",
  },
  {
    id: "sis_vi3",
    name: "Red Label 70cl",
    description: "",
    price: "4000₺",
    category: "Şişeler",
    subcategory: "Viski",
  },
  {
    id: "sis_vi4",
    name: "Jack Daniels 70cl",
    description: "",
    price: "5000₺",
    category: "Şişeler",
    subcategory: "Viski",
  },
  {
    id: "sis_vi5",
    name: "Red Label 35cl",
    description: "4 adet soft içecek, karışık çerez, napoliten, jelibon ve meyve tahtası eşliğinde",
    price: "2300₺",
    category: "Şişeler",
    subcategory: "Viski",
  },
  {
    id: "sis_te1",
    name: "Olmeca Blanco",
    description: "",
    price: "3500₺",
    category: "Şişeler",
    subcategory: "Tekila",
  },
  // --- KAHVELER ---
  {
    id: "khv_1",
    name: "Türk Kahvesi",
    description: "",
    price: "90₺",
    category: "Kahveler",
  },
  {
    id: "khv_2",
    name: "Double Espresso",
    description: "",
    price: "120₺",
    category: "Kahveler",
  },
  {
    id: "khv_3",
    name: "Damla Sakızlı Türk Kahvesi",
    description: "",
    price: "95₺",
    category: "Kahveler",
  },
  {
    id: "khv_4",
    name: "Machiato",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  {
    id: "khv_5",
    name: "Americano",
    description: "",
    price: "125₺",
    category: "Kahveler",
  },
  {
    id: "khv_6",
    name: "Coffe Latte",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  {
    id: "khv_7",
    name: "Coffe Mocha",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  {
    id: "khv_8",
    name: "Coffe White Mocha",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  {
    id: "khv_9",
    name: "Flat White",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  {
    id: "khv_10",
    name: "Double Türk Kahvesi",
    description: "",
    price: "125₺",
    category: "Kahveler",
  },
  {
    id: "khv_11",
    name: "Cappuccino",
    description: "",
    price: "135₺",
    category: "Kahveler",
  },
  // --- ÇAYLAR ---
  {
    id: "cy_1",
    name: "Çay",
    description: "",
    price: "35₺",
    category: "Çaylar",
    subcategory: "Klasik",
  },
  {
    id: "cy_2",
    name: "Fincan Çay",
    description: "",
    price: "45₺",
    category: "Çaylar",
    subcategory: "Klasik",
  },
  {
    id: "cy_3",
    name: "Sahlep",
    description: "",
    price: "145₺",
    category: "Çaylar",
    subcategory: "Klasik",
  },
  {
    id: "cy_4",
    name: "Sıcak Çikolata",
    description: "",
    price: "125₺",
    category: "Çaylar",
    subcategory: "Klasik",
  },
  {
    id: "cy_5",
    name: "Sıcak Beyaz Çikolata",
    description: "",
    price: "130₺",
    category: "Çaylar",
    subcategory: "Klasik",
  },
  // --- BİTKİ ÇAYLARI ---
  {
    id: "bc_1",
    name: "Ada Çayı",
    description: "",
    price: "145₺",
    category: "Çaylar",
    subcategory: "Bitki Çayları",
  },
  {
    id: "bc_2",
    name: "Ihlamur Çayı",
    description: "",
    price: "140₺",
    category: "Çaylar",
    subcategory: "Bitki Çayları",
  },
  {
    id: "bc_3",
    name: "Kuş Burnu Çayı",
    description: "",
    price: "140₺",
    category: "Çaylar",
    subcategory: "Bitki Çayları",
  },
  {
    id: "bc_4",
    name: "Kış Çayı",
    description: "",
    price: "145₺",
    category: "Çaylar",
    subcategory: "Bitki Çayları",
  },
  // --- SHOTLAR ---
  // Vodka Shotlar
  {
    id: "shot_vo_1",
    name: "Absolut Shot",
    description: "",
    price: "240₺",
    category: "Shotlar",
    subcategory: "Vodka Shotlar",
  },
  // Likör Shotlar
  {
    id: "shot_li_1",
    name: "Baileys Shot",
    description: "",
    price: "160₺",
    category: "Shotlar",
    subcategory: "Likör Shotlar",
  },
  {
    id: "shot_li_2",
    name: "Jagermeister Shot",
    description: "",
    price: "240₺",
    category: "Shotlar",
    subcategory: "Likör Shotlar",
  },
  // Cin Shotlar
  {
    id: "shot_gi_1",
    name: "Beefeater Gin Shot",
    description: "",
    price: "175₺",
    category: "Shotlar",
    subcategory: "Cin Shotlar",
  },
  // Tekila Shotlar
  {
    id: "shot_te_1",
    name: "Olmeca Blanco Shot",
    description: "",
    price: "225₺",
    category: "Shotlar",
    subcategory: "Tekila Shotlar",
  },
  {
    id: "shot_te_2",
    name: "Olmeca Gold Shot",
    description: "",
    price: "225₺",
    category: "Shotlar",
    subcategory: "Tekila Shotlar",
  },
  // Viski Shotlar
  {
    id: "shot_wi_1",
    name: "Chivas 12yr Shot",
    description: "",
    price: "210₺",
    category: "Shotlar",
    subcategory: "Viski Shotlar",
  },
  {
    id: "shot_wi_2",
    name: "Ballantines Shot",
    description: "",
    price: "150₺",
    category: "Shotlar",
    subcategory: "Viski Shotlar",
  },
  {
    id: "shot_wi_3",
    name: "Jack Daniels Shot",
    description: "",
    price: "170₺",
    category: "Shotlar",
    subcategory: "Viski Shotlar",
  },
  {
    id: "shot_wi_4",
    name: "Red Label Shot",
    description: "",
    price: "150₺",
    category: "Shotlar",
    subcategory: "Viski Shotlar",
  },
];

export const CAMPAIGNS: Campaign[] = [
  {
    id: "c1",
    title: "Happy Hour",
    description: "HAFTANIN HERGÜNÜ CUMARTESİ HARİÇ TUBORG ŞİŞE SAAT 19:00 'A KADAR 150 TL",
    image: "/happy-hour.jpg",
    category: "Biralar"
  },
  {
    id: "c2",
    title: "1+1 Tavuk Kampanyası",
    description: "SEÇEĞİNİZ TÜM TAVUK YEMEKLERİNDE 1 ALANA 1 BEDAVA SADECE CUMARTESİ HARİÇ SAAT 19:00'A KADAR",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&q=80&w=800",
    category: "Yemekler"
  },
  {
    id: "c3",
    title: "1+1 Pizza",
    description: "Salı ve Perşembe akşamları seçili pizzalarda bir alana bir bedava!",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800",
    category: "Yemekler"
  }
];

export const HEROSLIDES: HeroSlide[] = [
  {
    id: "h1",
    subtitle: "LEZZETİN",
    title: "EN SICAK",
    highlight: "HALİ!",
    description: "Taptaze malzemelerle, usta dokunuşlarla hazırlanır.",
    image: "https://i.ibb.co/5WyWMV25/633704765-1231353942398456-5640972076518561394-n.jpg",
    buttonText: "MENÜYE GİT"
  },
  {
    id: "h2",
    subtitle: "HAFTANIN HER GÜNÜ",
    title: "HAPPY",
    highlight: "HOUR!",
    description: "CUMARTESİ HARİÇ TUBORG ŞİŞE SAAT 19:00 'A KADAR 150 TL",
    image: "/happy-hour.jpg",
    buttonText: "MENÜYE GİT"
  },
  {
    id: "h3",
    subtitle: "1 ALANA 1 BEDAVA",
    title: "1+1 TAVUK",
    highlight: "KAMPANYASI",
    description: "SEÇEĞİNİZ TÜM TAVUK YEMEKLERİNDE SADECE CUMARTESİ HARİÇ SAAT 19:00'A KADAR!",
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&q=80&w=1200",
    buttonText: "MENÜYE GİT"
  }
];

export const EVENTS: Event[] = [
  {
    id: "e1",
    title: "DJ Performance: Night Vibes",
    date: "28 Nisan Cuma",
    time: "21:30",
    description: "Görükle'nin en iyi DJ setleri ile geceye hazır olun.",
  },
  {
    id: "e2",
    title: "Live Jazz Night",
    date: "30 Nisan Pazar",
    time: "20:00",
    description: "Bahçemizde huzurlu bir akşam için canlı caz keyfi.",
  }
];
